config/routes.rb
Railstest::Application.routes.draw do
  get "home/index"

  resources :users do
    member do
      get :posts
    end
  end
  resources :posts do
    resources :comments
  end

  root :to => 'home#index'

  match 'login', :to => 'users#login', :via => [:get, :post]
  match 'logout', :to => 'users#logout', :via => [:get]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title, :user_id

  validates :title, :presence => true,
                    :length => { :minimum => 5 }

  belongs_to :user
  has_many :comments, :dependent => :destroy
end

app/models/user.rb
# encoding: utf-8
class User < ActiveRecord::Base
  attr_accessible :password, :username
  
  validates :username, :presence => true, :length => { :minimum => 4, :message => "は４文字以上の必要があります"},
    :uniqueness => true ,
    :format => { :with => /^[a-zA-Z0-9]+$/, :message => "は半角英数のみです" }

  validates :password,
    :format => { :with => /^[!-~]+$/, :message => "は半角英数記号のみです"}

  has_many :posts, :dependent => :destroy

  def self.authenticate(username, password)
    u = get_user(username)
    if !u.nil?
      if u.password == password
        return u
      end
    end
    return nil
  end

  def self.get_user_name(id)
    if !id.nil?
      u = find_by_id(id)
      if !u.nil?
        return u.username 
      end
    end
    return "?unknown User?"
  end

  def self.get_user(id)
    if !id.nil?
      u = find_by_id(id)
      return u
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def login_required
    if session[:user_id]
      return true
    end
    flash[:warning] = "Login"
    session[:return_to] = request.fullpath
    redirect_to :login
    return false
  end

  def redirect_to_stored
    if session[:return_to]
      return_to = session[:return_to]
      session[:return_to] = nil
      redirect_to return_to
    else
      redirect_to posts_path 
    end
  end  

  def id_check(id)
    if session[:user_id] == id
      return true
    else
      return false 
    end
  end
end

app/controllers/comments_controller.rb
# encoding: utf-8
class CommentsController < ApplicationController
  before_filter :login_required

  def index
    respond_to posts_path
  end

  def create

    if request.post?
      @post = Post.find(params[:post_id])
      @comment = @post.comments.build
      @comment.user_id = session[:user_id]
      @comment.content = params[:content]
      if @comment.save
      end
      redirect_to post_path(@post)
    else
      redirect_to post_path(@post)
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    if id_check(@comment.user_id)
      post_id = @comment.post_id
      @comment.destroy

      respond_to do |format|
        format.html { redirect_to post_path(post_id), :notice => "コメントを削除しました" }
        format.json { head :no_content }
      end
    else
      redirect_to @post, :alert => "他人のコメントは削除できません"
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
# encoding: utf-8
class PostsController < ApplicationController
  before_filter :login_required, :except => ['index','show']

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order("updated_at").reverse_order

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @is_owner = id_check(@post.user_id)
    commentsall = @post.comments.all
    @comments = Array.new
    commentsall.each do |c|
      @comments.push([c, id_check(c.user_id) ])
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])

    if !id_check(@post.user_id)
      redirect_to @post, :alert => "他人の投稿は編集できません"
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    u = User.get_user(session[:user_id])
    @post = u.posts.build(params[:post])
    # @post = Post.new(params[:post])

    @post[:name] = User.get_user_name(u.id)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: '投稿を削除しました' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    if id_check(@post.user_id)
      @post.destroy

      respond_to do |format|
        format.html { redirect_to posts_url }
        format.json { head :no_content }
      end
    else
      redirect_to @post, :alert => "他人の投稿は削除できません"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end
 
  # GET /users/new
  def new
    @user = User.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def login
    if request.post?
      session[:user_id] = nil
      ret = User.authenticate(params[:userid], params[:password])
      if ret
        flash[:message] = "Login Successful"
        session[:user_id] = ret.id
        redirect_to_stored
      else
        flash[:warning] = "Login failed"
      end
    end 
  end

  def logout
    session[:user_id] = nil
    redirect_to :root
  end

  def posts
    u = User.find_by_id(params[:id])
    @username = User.get_user_name(u.id)
    @post_array = u.posts.order('updated_at').reverse_order
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Hello Rails</h1>
<%= link_to "My Blog", posts_path %>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railstest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Name <br />
    <%= User.get_user_name(session[:user_id]) %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>新着投稿一覧</h1>
<p id="notice"><%= flash[:alert] %></p>
<p id="notice"><%= flash[:notice] %></p>
<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Content</th>
    <th>Updated Time</th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td>
      <%= link_to User.get_user_name(post.user_id), posts_user_path(post.user_id) %>
    </td>
    <td><%= link_to post.title, post %></td>
    <td><%= post.content %></td>
    <td><%= post.updated_at %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '投稿する', new_post_path %>
<%= link_to 'ユーザー一覧', users_path %>

<br />

<% if session[:user_id] %>
  <i><%= User.get_user_name(session[:user_id])%>としてログイン中</i></br>
  <%= link_to 'ログアウトする', :logout %>
<% else %>
ログインしていません
  <%= link_to 'ログインする', :login %>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= flash[:alert] %></p>
<p id="notice"><%= flash[:notice] %></p>

<h2>
  <%= @post.title %>
</h2>
<p align = "right">
by 
<%= User.get_user_name(@post.user_id) %>
(<%= @post.updated_at %>)
</p>
<p align = "center">
<%= @post.content %>
</p>
<hr>

<% if @is_owner %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<h3>コメント：</h3>
<% @comments.each do |c| %>
  <%
  content = c[0].content
  username = User.get_user_name(c[0].user_id)
  is_owner = c[1]
%>
  <p><b><%= content %></b> by <%= username %>
  <% if is_owner %>
    <%= link_to ' <Destroy>', [c[0].post, c[0]], method: :delete, data: { confirm: 'コメントを削除しますか？' } %>
  <% end %>
  </p>
<% end %>

<%= form_tag(params[:id] + "/comments", :method => "post") do %>
  <div class="field">
    <%= label_tag(:content, "コメント") %><br />
    <%= text_area_tag(:content)%>
  </div>
  <div class="actions">
    <%= submit_tag("コメントする") %>
  </div>
<% end %>

<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>

<table>
  <tr>
    <th>User ID</th>
    <th>Password</th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td>
      <%= link_to user.username, posts_user_path(user) %>
    </td>
    <td><%= user.password %></td>
    <td><%= link_to 'ユーザーを削除', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Users', new_user_path %>

app/views/users/login.html.erb
<%= form_tag("/login", :method => "post") do %>
  <%= label_tag(:userid, "ユーザーID") %>
  <%= text_field_tag(:userid)%>
  <%= label_tag(:password, "ぱすわーど") %>
  <%= password_field_tag(:password) %>
  <%= submit_tag("ログイン！") %>
<% end %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/posts.html.erb
<h1> <%= @username %>の投稿一覧</h1></br>

<% @post_array.each do |post| %>
	<hr>
	<h2>
	<%= link_to post.title, post %>
	</h2>
	<p align = "right">
	<%= post.updated_at %>
	</p>
	<p align = "center">
	<%= post.content %>
	</p>
<% end %>

<%= link_to 'ユーザー一覧', users_path %>
<%= link_to '新着投稿一覧', posts_path %>